export enum Types {
  ADD_ENTRY = 'ADD_ENTRY',
  EDIT_ENTRY = 'EDIT_ENTRY',
  DELETE_ENTRY = 'DELETE_ENTRY',
  VIEW_TIME_LAPSE = 'VIEW_TIME_LAPSE',
  VIEW_TIMELINE = 'VIEW_TIMELINE',
  VISIBILITY_TOGGLE_ADD_ENTRY = 'VISIBILITY_TOGGLE_ADD_ENTRY',
  SHOW_ENTRY_DETAILS = 'SHOW_ENTRY_DETAILS',
  HIDE_ENTRY_DETAILS = 'HIDE_ENTRY_DETAILS',
}
